<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	targetNamespace="urn:iso:std:iso-iec:24727:tech:schema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:iso="urn:iso:std:iso-iec:24727:tech:schema"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- =================== -->
	<!-- Definition of types -->
	<!-- (only include XSDs) -->
	<!-- =================== -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified"
			targetNamespace="urn:iso:std:iso-iec:24727:tech:schema">
			<xsd:include schemaLocation="CardInfoRepository.xsd" />
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		</xsd:schema>
	</wsdl:types>

	<!-- ====================== -->
	<!-- Definition of messages -->
	<!-- ====================== -->

	<wsdl:message name="GetCardInfoOrACDRequest">
		<wsdl:part name="parameters" element="iso:GetCardInfoOrACD" />
	</wsdl:message>
	<wsdl:message name="GetCardInfoOrACDResponse">
		<wsdl:part name="parameters"
			element="iso:GetCardInfoOrACDResponse" />
	</wsdl:message>

	<!-- ====================== -->
	<!-- Definition of portType -->
	<!-- ====================== -->


	<wsdl:portType name="GetCardInfoOrACD">
		<wsdl:operation name="GetCardInfoOrACD">
			<wsdl:input message="iso:GetCardInfoOrACDRequest" />
			<wsdl:output message="iso:GetCardInfoOrACDResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<!-- ===================== -->
	<!-- Definition of Binding -->
	<!-- ===================== -->

	<wsdl:binding name="GetCardInfoOrACD" type="iso:GetCardInfoOrACD">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="GetCardInfoOrACD">
			<soap:operation
				soapAction="urn:iso:std:iso-iec:24727:tech:schema:GetCardInfoOrACD" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<!-- Definition of CardInfoOrACD-Service -->

	<wsdl:service name="GetCardInfoOrACD">
		<wsdl:port name="GetCardInfoOrACD"
			binding="iso:GetCardInfoOrACD">
			<soap:address location="http://127.0.0.1:18080" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
