package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_DSA_PARAMETER_GEN_PARAM extends Structure {
	/** C type : CK_MECHANISM_TYPE */
	public long hash;
	public long getHash() {
		return hash;
	}
	public void setHash(long hash) {
		this.hash = hash;
	}
	/** C type : CK_BYTE_PTR */
	public Pointer pSeed;
	public Pointer getPSeed() {
		return pSeed;
	}
	public void setPSeed(Pointer pSeed) {
		this.pSeed = pSeed;
	}
	/** C type : CK_ULONG */
	public long ulSeedLen;
	public long getUlSeedLen() {
		return ulSeedLen;
	}
	public void setUlSeedLen(long ulSeedLen) {
		this.ulSeedLen = ulSeedLen;
	}
	/** C type : CK_ULONG */
	public long ulIndex;
	public long getUlIndex() {
		return ulIndex;
	}
	public void setUlIndex(long ulIndex) {
		this.ulIndex = ulIndex;
	}
	public CK_DSA_PARAMETER_GEN_PARAM() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("hash", "pSeed", "ulSeedLen", "ulIndex");
	}
	/**
	 * @param hash C type : CK_MECHANISM_TYPE<br>
	 * @param pSeed C type : CK_BYTE_PTR<br>
	 * @param ulSeedLen C type : CK_ULONG<br>
	 * @param ulIndex C type : CK_ULONG
	 */
	public CK_DSA_PARAMETER_GEN_PARAM(long hash, Pointer pSeed, long ulSeedLen, long ulIndex) {
		super();
		this.hash = hash;
		this.pSeed = pSeed;
		this.ulSeedLen = ulSeedLen;
		this.ulIndex = ulIndex;
	}
	public CK_DSA_PARAMETER_GEN_PARAM(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_DSA_PARAMETER_GEN_PARAM implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_DSA_PARAMETER_GEN_PARAM implements Structure.ByValue {
		
	};
}
