package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_GOSTR3410_KEY_WRAP_PARAMS extends Structure {
	/** C type : CK_BYTE_PTR */
	public Pointer pWrapOID;
	public Pointer getPWrapOID() {
		return pWrapOID;
	}
	public void setPWrapOID(Pointer pWrapOID) {
		this.pWrapOID = pWrapOID;
	}
	/** C type : CK_ULONG */
	public long ulWrapOIDLen;
	public long getUlWrapOIDLen() {
		return ulWrapOIDLen;
	}
	public void setUlWrapOIDLen(long ulWrapOIDLen) {
		this.ulWrapOIDLen = ulWrapOIDLen;
	}
	/** C type : CK_BYTE_PTR */
	public Pointer pUKM;
	public Pointer getPUKM() {
		return pUKM;
	}
	public void setPUKM(Pointer pUKM) {
		this.pUKM = pUKM;
	}
	/** C type : CK_ULONG */
	public long ulUKMLen;
	public long getUlUKMLen() {
		return ulUKMLen;
	}
	public void setUlUKMLen(long ulUKMLen) {
		this.ulUKMLen = ulUKMLen;
	}
	/** C type : CK_OBJECT_HANDLE */
	public long hKey;
	public long getHKey() {
		return hKey;
	}
	public void setHKey(long hKey) {
		this.hKey = hKey;
	}
	public CK_GOSTR3410_KEY_WRAP_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("pWrapOID", "ulWrapOIDLen", "pUKM", "ulUKMLen", "hKey");
	}
	/**
	 * @param pWrapOID C type : CK_BYTE_PTR<br>
	 * @param ulWrapOIDLen C type : CK_ULONG<br>
	 * @param pUKM C type : CK_BYTE_PTR<br>
	 * @param ulUKMLen C type : CK_ULONG<br>
	 * @param hKey C type : CK_OBJECT_HANDLE
	 */
	public CK_GOSTR3410_KEY_WRAP_PARAMS(Pointer pWrapOID, long ulWrapOIDLen, Pointer pUKM, long ulUKMLen, long hKey) {
		super();
		this.pWrapOID = pWrapOID;
		this.ulWrapOIDLen = ulWrapOIDLen;
		this.pUKM = pUKM;
		this.ulUKMLen = ulUKMLen;
		this.hKey = hKey;
	}
	public CK_GOSTR3410_KEY_WRAP_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_GOSTR3410_KEY_WRAP_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_GOSTR3410_KEY_WRAP_PARAMS implements Structure.ByValue {
		
	};
}
