package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_KEY_DERIVATION_STRING_DATA extends Structure {
	/** C type : CK_BYTE_PTR */
	public Pointer pData;
	public Pointer getPData() {
		return pData;
	}
	public void setPData(Pointer pData) {
		this.pData = pData;
	}
	/** C type : CK_ULONG */
	public long ulLen;
	public long getUlLen() {
		return ulLen;
	}
	public void setUlLen(long ulLen) {
		this.ulLen = ulLen;
	}
	public CK_KEY_DERIVATION_STRING_DATA() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("pData", "ulLen");
	}
	/**
	 * @param pData C type : CK_BYTE_PTR<br>
	 * @param ulLen C type : CK_ULONG
	 */
	public CK_KEY_DERIVATION_STRING_DATA(Pointer pData, long ulLen) {
		super();
		this.pData = pData;
		this.ulLen = ulLen;
	}
	public CK_KEY_DERIVATION_STRING_DATA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_KEY_DERIVATION_STRING_DATA implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_KEY_DERIVATION_STRING_DATA implements Structure.ByValue {
		
	};
}
