package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_OTP_SIGNATURE_INFO extends Structure {
	/** C type : CK_OTP_PARAM_PTR */
	public org.openecard.mdlw.sal.cryptoki.CK_OTP_PARAM.ByReference pParams;
	public org.openecard.mdlw.sal.cryptoki.CK_OTP_PARAM.ByReference getPParams() {
		return pParams;
	}
	public void setPParams(org.openecard.mdlw.sal.cryptoki.CK_OTP_PARAM.ByReference pParams) {
		this.pParams = pParams;
	}
	/** C type : CK_ULONG */
	public long ulCount;
	public long getUlCount() {
		return ulCount;
	}
	public void setUlCount(long ulCount) {
		this.ulCount = ulCount;
	}
	public CK_OTP_SIGNATURE_INFO() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("pParams", "ulCount");
	}
	/**
	 * @param pParams C type : CK_OTP_PARAM_PTR<br>
	 * @param ulCount C type : CK_ULONG
	 */
	public CK_OTP_SIGNATURE_INFO(org.openecard.mdlw.sal.cryptoki.CK_OTP_PARAM.ByReference pParams, long ulCount) {
		super();
		this.pParams = pParams;
		this.ulCount = ulCount;
	}
	public CK_OTP_SIGNATURE_INFO(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_OTP_SIGNATURE_INFO implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_OTP_SIGNATURE_INFO implements Structure.ByValue {
		
	};
}
