package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_RC2_MAC_GENERAL_PARAMS extends Structure {
	/**
	 * effective bits (1-1024)<br>
	 * C type : CK_ULONG
	 */
	public long ulEffectiveBits;
	public long getUlEffectiveBits() {
		return ulEffectiveBits;
	}
	public void setUlEffectiveBits(long ulEffectiveBits) {
		this.ulEffectiveBits = ulEffectiveBits;
	}
	/**
	 * Length of MAC in bytes<br>
	 * C type : CK_ULONG
	 */
	public long ulMacLength;
	public long getUlMacLength() {
		return ulMacLength;
	}
	public void setUlMacLength(long ulMacLength) {
		this.ulMacLength = ulMacLength;
	}
	public CK_RC2_MAC_GENERAL_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("ulEffectiveBits", "ulMacLength");
	}
	/**
	 * @param ulEffectiveBits effective bits (1-1024)<br>
	 * C type : CK_ULONG<br>
	 * @param ulMacLength Length of MAC in bytes<br>
	 * C type : CK_ULONG
	 */
	public CK_RC2_MAC_GENERAL_PARAMS(long ulEffectiveBits, long ulMacLength) {
		super();
		this.ulEffectiveBits = ulEffectiveBits;
		this.ulMacLength = ulMacLength;
	}
	public CK_RC2_MAC_GENERAL_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_RC2_MAC_GENERAL_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_RC2_MAC_GENERAL_PARAMS implements Structure.ByValue {
		
	};
}
