<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	targetNamespace="urn:iso:std:iso-iec:24727:tech:schema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:iso="urn:iso:std:iso-iec:24727:tech:schema"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- =================== -->
	<!-- Definition of types -->
	<!-- (only include XSDs) -->
	<!-- =================== -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified"
			targetNamespace="urn:iso:std:iso-iec:24727:tech:schema">
			<xsd:include schemaLocation="ISOIFDCallback.xsd" />
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
		</xsd:schema>
	</wsdl:types>

	<!-- ====================== -->
	<!-- Definition of messages -->
	<!-- ====================== -->

	<wsdl:message name="SignalEvent">
		<wsdl:part name="parameters" element="iso:SignalEvent" />
	</wsdl:message>
	<wsdl:message name="SignalEventResponse">
		<wsdl:part name="parameters" element="iso:SignalEventResponse" />
	</wsdl:message>

	<!-- ====================== -->
	<!-- Definition of portType -->
	<!-- ====================== -->

	<wsdl:portType name="IFDCallback">

		<wsdl:operation name="SignalEvent">
			<wsdl:input message="iso:SignalEvent" />
			<wsdl:output message="iso:SignalEventResponse" />
		</wsdl:operation>

	</wsdl:portType>



	<!-- ===================== -->
	<!-- Definition of Binding -->
	<!-- ===================== -->

	<wsdl:binding name="IFDCallback" type="iso:IFDCallback">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />


		<wsdl:operation name="SignalEvent">
			<soap:operation
				soapAction="urn:iso:std:iso-iec:24727:tech:schema:SignalEvent" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>


	</wsdl:binding>


	<!-- Definition of IFDCallback-Service -->

	<wsdl:service name="IFDCallback">
		<wsdl:port name="IFDCallbackPort" binding="iso:IFDCallback">
			<soap:address location="http://127.0.0.1:18080" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
