<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.bsi.bund.de/ecard/api/1.1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:ec="http://www.bsi.bund.de/ecard/api/1.1"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

	<!-- =================== -->
	<!-- Definition of types -->
	<!-- (only include XSDs) -->
	<!-- =================== -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			elementFormDefault="qualified"
			targetNamespace="http://www.bsi.bund.de/ecard/api/1.1">
			<xsd:include schemaLocation="Management.xsd" />
		</xsd:schema>
	</wsdl:types>

	<!-- ====================== -->
	<!-- Definition of messages -->
	<!-- ====================== -->

	<!-- CheckFrameworkUpdate (vgl. [eCard-3], Anhang A) -->
	<wsdl:message name="CheckFrameworkUpdate">
		<wsdl:part name="parameters" element="ec:CheckFrameworkUpdate" />
	</wsdl:message>
	<wsdl:message name="CheckFrameworkUpdateResponse">
		<wsdl:part name="parameters"
			element="ec:CheckFrameworkUpdateResponse" />
	</wsdl:message>


	<!-- ====================== -->
	<!-- Definition of portType -->
	<!-- ====================== -->

	<wsdl:portType name="UpdateService">

		<!-- CheckFrameworkUpdate -->
		<wsdl:operation name="CheckFrameworkUpdate">
			<wsdl:input message="ec:CheckFrameworkUpdate" />
			<wsdl:output message="ec:CheckFrameworkUpdateResponse" />
		</wsdl:operation>

	</wsdl:portType>



	<!-- ===================== -->
	<!-- Definition of Binding -->
	<!-- ===================== -->

	<wsdl:binding name="UpdateService" type="ec:UpdateService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />


		<!-- CheckFrameworkUpdate -->
		<wsdl:operation name="CheckFrameworkUpdate">
			<soap:operation
				soapAction="http://www.bsi.bund.de/ecard/api/1.0#CheckFrameworkUpdate" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>



	</wsdl:binding>


	<!-- Definition of UpdateService-Service -->

	<wsdl:service name="UpdateService">
		<wsdl:port name="UpdateServicePort"
			binding="ec:UpdateService">
			<soap:address location="http://127.0.0.1:24727" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
