package org.openecard.ws;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@XmlSeeAlso({org.w3._2007._05.xmldsig_more_.ObjectFactory.class, org.w3._2001._04.xmlenc_.ObjectFactory.class, de.bund.bsi.ecard.api._1.ObjectFactory.class, org.etsi.uri._01903.v1_3.ObjectFactory.class, oasis.names.tc.dss_x._1_0.profiles.verificationreport.schema_.ObjectFactory.class, org.openecard.ws.schema.ObjectFactory.class, org.openecard.ws.chipgateway.ObjectFactory.class, org.w3._2001._04.xmldsig_more_.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, generated.ObjectFactory.class, iso.std.iso_iec._24727.tech.schema.ObjectFactory.class, org.w3._2009.xmlenc11_.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, org.etsi.uri._02231.v3_1.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
public interface IFD {

    @ECardApiMethod(operationName = "ReleaseContext", action = "urn:iso:std:iso-iec:24727:tech:schema:ReleaseContext")
    public iso.std.iso_iec._24727.tech.schema.ReleaseContextResponse releaseContext(
        iso.std.iso_iec._24727.tech.schema.ReleaseContext parameters
    );

    @ECardApiMethod(operationName = "EndTransaction", action = "urn:iso:std:iso-iec:24727:tech:schema:EndTransaction")
    public iso.std.iso_iec._24727.tech.schema.EndTransactionResponse endTransaction(
        iso.std.iso_iec._24727.tech.schema.EndTransaction parameters
    );

    /**
     * Prepare devices, so they can be used and connected to.
     * This is intended to handle iOS style APIs where the card can only be used for a very short time and no permament
     * connection is desireable. There one would start a session and once that is present the IFD can connect to the card.
     */
    @ECardApiMethod(operationName = "PrepareDevices", action = "urn:iso:std:iso-iec:24727:tech:schema:PrepareDevices")
    public iso.std.iso_iec._24727.tech.schema.PrepareDevicesResponse prepareDevices(
	iso.std.iso_iec._24727.tech.schema.PrepareDevices parameters
    );

    /**
     * Power down any previously prepared devices.
     * This is the companion operation to PrepareDevices.
     */
    @ECardApiMethod(operationName = "PowerDownDevices", action = "urn:iso:std:iso-iec:24727:tech:schema:PowerDownDevices")
    public iso.std.iso_iec._24727.tech.schema.PowerDownDevicesResponse powerDownDevices(
	iso.std.iso_iec._24727.tech.schema.PowerDownDevices parameters
    );

    @ECardApiMethod(operationName = "ListIFDs", action = "urn:iso:std:iso-iec:24727:tech:schema:ListIFDs")
    public iso.std.iso_iec._24727.tech.schema.ListIFDsResponse listIFDs(
        iso.std.iso_iec._24727.tech.schema.ListIFDs parameters
    );

    @ECardApiMethod(operationName = "Transmit", action = "urn:iso:std:iso-iec:24727:tech:schema:Transmit")
    public iso.std.iso_iec._24727.tech.schema.TransmitResponse transmit(
        iso.std.iso_iec._24727.tech.schema.Transmit parameters
    );

    @ECardApiMethod(operationName = "ModifyVerificationData", action = "urn:iso:std:iso-iec:24727:tech:schema:ModifyVerificationData")
    public iso.std.iso_iec._24727.tech.schema.ModifyVerificationDataResponse modifyVerificationData(
        iso.std.iso_iec._24727.tech.schema.ModifyVerificationData parameters
    );

    @ECardApiMethod(operationName = "Cancel", action = "urn:iso:std:iso-iec:24727:tech:schema:Cancel")
    public iso.std.iso_iec._24727.tech.schema.CancelResponse cancel(
        iso.std.iso_iec._24727.tech.schema.Cancel parameters
    );

    @ECardApiMethod(operationName = "ControlIFD", action = "urn:iso:std:iso-iec:24727:tech:schema:ControlIFD")
    public iso.std.iso_iec._24727.tech.schema.ControlIFDResponse controlIFD(
        iso.std.iso_iec._24727.tech.schema.ControlIFD parameters
    );

    @ECardApiMethod(operationName = "Connect", action = "urn:iso:std:iso-iec:24727:tech:schema:Connect")
    public iso.std.iso_iec._24727.tech.schema.ConnectResponse connect(
        iso.std.iso_iec._24727.tech.schema.Connect parameters
    );

    @ECardApiMethod(operationName = "VerifyUser", action = "urn:iso:std:iso-iec:24727:tech:schema:VerifyUser")
    public iso.std.iso_iec._24727.tech.schema.VerifyUserResponse verifyUser(
        iso.std.iso_iec._24727.tech.schema.VerifyUser parameters
    );

    @ECardApiMethod(operationName = "EstablishContext", action = "urn:iso:std:iso-iec:24727:tech:schema:EstablishContext")
    public iso.std.iso_iec._24727.tech.schema.EstablishContextResponse establishContext(
        iso.std.iso_iec._24727.tech.schema.EstablishContext parameters
    );

    @ECardApiMethod(operationName = "Wait", action = "urn:iso:std:iso-iec:24727:tech:schema:Wait")
    public iso.std.iso_iec._24727.tech.schema.WaitResponse wait(
        iso.std.iso_iec._24727.tech.schema.Wait parameters
    );

    @ECardApiMethod(operationName = "GetStatus", action = "urn:iso:std:iso-iec:24727:tech:schema:GetStatus")
    public iso.std.iso_iec._24727.tech.schema.GetStatusResponse getStatus(
        iso.std.iso_iec._24727.tech.schema.GetStatus parameters
    );

    @ECardApiMethod(operationName = "GetIFDCapabilities", action = "urn:iso:std:iso-iec:24727:tech:schema:GetIFDCapabilities")
    public iso.std.iso_iec._24727.tech.schema.GetIFDCapabilitiesResponse getIFDCapabilities(
        iso.std.iso_iec._24727.tech.schema.GetIFDCapabilities parameters
    );

    @ECardApiMethod(operationName = "BeginTransaction", action = "urn:iso:std:iso-iec:24727:tech:schema:BeginTransaction")
    public iso.std.iso_iec._24727.tech.schema.BeginTransactionResponse beginTransaction(
        iso.std.iso_iec._24727.tech.schema.BeginTransaction beginTransaction
    );

    @ECardApiMethod(operationName = "Disconnect", action = "urn:iso:std:iso-iec:24727:tech:schema:Disconnect")
    public iso.std.iso_iec._24727.tech.schema.DisconnectResponse disconnect(
        iso.std.iso_iec._24727.tech.schema.Disconnect parameters
    );

    @ECardApiMethod(operationName = "EstablishChannel", action = "urn:iso:std:iso-iec:24727:tech:schema:EstablishChannel")
    public iso.std.iso_iec._24727.tech.schema.EstablishChannelResponse establishChannel(
        iso.std.iso_iec._24727.tech.schema.EstablishChannel parameters
    );

    @ECardApiMethod(operationName = "DestroyChannel", action = "urn:iso:std:iso-iec:24727:tech:schema:DestroyChannel")
    public iso.std.iso_iec._24727.tech.schema.DestroyChannelResponse destroyChannel(
        iso.std.iso_iec._24727.tech.schema.DestroyChannel parameters
    );

    @ECardApiMethod(operationName = "Output", action = "urn:iso:std:iso-iec:24727:tech:schema:Output")
    public iso.std.iso_iec._24727.tech.schema.OutputResponse output(
        iso.std.iso_iec._24727.tech.schema.Output parameters
    );
}
