package org.openecard.ws;

import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@XmlSeeAlso({org.w3._2007._05.xmldsig_more_.ObjectFactory.class, org.w3._2001._04.xmlenc_.ObjectFactory.class, de.bund.bsi.ecard.api._1.ObjectFactory.class, org.etsi.uri._01903.v1_3.ObjectFactory.class, oasis.names.tc.dss_x._1_0.profiles.verificationreport.schema_.ObjectFactory.class, org.openecard.ws.schema.ObjectFactory.class, org.openecard.ws.chipgateway.ObjectFactory.class, org.w3._2001._04.xmldsig_more_.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, generated.ObjectFactory.class, iso.std.iso_iec._24727.tech.schema.ObjectFactory.class, org.w3._2009.xmlenc11_.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, org.etsi.uri._02231.v3_1.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
public interface Management {

    @ECardApiMethod(operationName = "GetOCSPServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetOCSPServices")
    public de.bund.bsi.ecard.api._1.GetOCSPServicesResponse getOCSPServices(
        de.bund.bsi.ecard.api._1.GetOCSPServices parameters
    );

    @ECardApiMethod(operationName = "DeleteTrustedViewer", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteTrustedViewer")
    public de.bund.bsi.ecard.api._1.DeleteTrustedViewerResponse deleteTrustedViewer(
        de.bund.bsi.ecard.api._1.DeleteTrustedViewer parameters
    );

    @ECardApiMethod(operationName = "TerminateFramework", action = "http://www.bsi.bund.de/ecard/api/1.0#TerminateFramework")
    public de.bund.bsi.ecard.api._1.TerminateFrameworkResponse terminateFramework(
        de.bund.bsi.ecard.api._1.TerminateFramework parameters
    );

    @ECardApiMethod(operationName = "SetTrustedViewerConfiguration", action = "http://www.bsi.bund.de/ecard/api/1.0#SetTrustedViewerConfiguration")
    public de.bund.bsi.ecard.api._1.SetTrustedViewerConfigurationResponse setTrustedViewerConfiguration(
        de.bund.bsi.ecard.api._1.SetTrustedViewerConfiguration parameters
    );

    @ECardApiMethod(operationName = "GetDefaultParameters", action = "http://www.bsi.bund.de/ecard/api/1.0#GetDefaultParameters")
    public de.bund.bsi.ecard.api._1.GetDefaultParametersResponse getDefaultParameters(
        de.bund.bsi.ecard.api._1.GetDefaultParameters parameters
    );

    @ECardApiMethod(operationName = "SetOCSPServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetOCSPServices")
    public de.bund.bsi.ecard.api._1.SetOCSPServicesResponse setOCSPServices(
        de.bund.bsi.ecard.api._1.SetOCSPServices parameters
    );

    @ECardApiMethod(operationName = "InitializeFramework", action = "http://www.bsi.bund.de/ecard/api/1.0#InitializeFramework")
    public de.bund.bsi.ecard.api._1.InitializeFrameworkResponse initializeFramework(
        de.bund.bsi.ecard.api._1.InitializeFramework parameters
    );

    @ECardApiMethod(operationName = "AddCardInfoFiles", action = "http://www.bsi.bund.de/ecard/api/1.0#AddCardInfoFiles")
    public de.bund.bsi.ecard.api._1.AddCardInfoFilesResponse addCardInfoFiles(
        de.bund.bsi.ecard.api._1.AddCardInfoFiles parameters
    );

    @ECardApiMethod(operationName = "GetTrustedViewerConfiguration", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedViewerConfiguration")
    public de.bund.bsi.ecard.api._1.GetTrustedViewerConfigurationResponse getTrustedViewerConfiguration(
        de.bund.bsi.ecard.api._1.GetTrustedViewerConfiguration parameters
    );

    @ECardApiMethod(operationName = "UnregisterIFD", action = "http://www.bsi.bund.de/ecard/api/1.0#UnregisterIFD")
    public de.bund.bsi.ecard.api._1.UnregisterIFDResponse unregisterIFD(
        de.bund.bsi.ecard.api._1.UnregisterIFD parameters
    );

    @ECardApiMethod(operationName = "ExportTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#ExportTSL")
    public de.bund.bsi.ecard.api._1.ExportTSLResponse exportTSL(
        de.bund.bsi.ecard.api._1.ExportTSL parameters
    );

    @ECardApiMethod(operationName = "GetDirectoryServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetDirectoryServices")
    public de.bund.bsi.ecard.api._1.GetDirectoryServicesResponse getDirectoryServices(
        de.bund.bsi.ecard.api._1.GetDirectoryServices parameters
    );

    @ECardApiMethod(operationName = "ExportCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#ExportCertificate")
    public de.bund.bsi.ecard.api._1.ExportCertificateResponse exportCertificate(
        de.bund.bsi.ecard.api._1.ExportCertificate parameters
    );

    @ECardApiMethod(operationName = "DeleteTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteTSL")
    public de.bund.bsi.ecard.api._1.DeleteTSLResponse deleteTSL(
        de.bund.bsi.ecard.api._1.DeleteTSL parameters
    );

    @ECardApiMethod(operationName = "GetTSServices", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTSServices")
    public de.bund.bsi.ecard.api._1.GetTSServicesResponse getTSServices(
        de.bund.bsi.ecard.api._1.GetTSServices parameters
    );

    @ECardApiMethod(operationName = "AddTSL", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTSL")
    public de.bund.bsi.ecard.api._1.AddTSLResponse addTSL(
        de.bund.bsi.ecard.api._1.AddTSL parameters
    );

    @ECardApiMethod(operationName = "APIACLModify", action = "http://www.bsi.bund.de/ecard/api/1.0#APIACLModify")
    public de.bund.bsi.ecard.api._1.APIACLModifyResponse apiaclModify(
        de.bund.bsi.ecard.api._1.APIACLModify parameters
    );

    @ECardApiMethod(operationName = "AddTrustedViewer", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTrustedViewer")
    public de.bund.bsi.ecard.api._1.AddTrustedViewerResponse addTrustedViewer(
        de.bund.bsi.ecard.api._1.AddTrustedViewer parameters
    );

    @ECardApiMethod(operationName = "GetTrustedViewerList", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedViewerList")
    public de.bund.bsi.ecard.api._1.GetTrustedViewerListResponse getTrustedViewerList(
        de.bund.bsi.ecard.api._1.GetTrustedViewerList parameters
    );

    @ECardApiMethod(operationName = "SetDirectoryServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetDirectoryServices")
    public de.bund.bsi.ecard.api._1.SetDirectoryServicesResponse setDirectoryServices(
        de.bund.bsi.ecard.api._1.SetDirectoryServices parameters
    );

    @ECardApiMethod(operationName = "GetTrustedIdentities", action = "http://www.bsi.bund.de/ecard/api/1.0#GetTrustedIdentities")
    public de.bund.bsi.ecard.api._1.GetTrustedIdentitiesResponse getTrustedIdentities(
        de.bund.bsi.ecard.api._1.GetTrustedIdentities parameters
    );

    @ECardApiMethod(operationName = "SetDefaultParameters", action = "http://www.bsi.bund.de/ecard/api/1.0#SetDefaultParameters")
    public de.bund.bsi.ecard.api._1.SetDefaultParametersResponse setDefaultParameters(
        de.bund.bsi.ecard.api._1.SetDefaultParameters parameters
    );

    @ECardApiMethod(operationName = "RegisterIFD", action = "http://www.bsi.bund.de/ecard/api/1.0#RegisterIFD")
    public de.bund.bsi.ecard.api._1.RegisterIFDResponse registerIFD(
        de.bund.bsi.ecard.api._1.RegisterIFD parameters
    );

    @ECardApiMethod(operationName = "DeleteCardInfoFiles", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteCardInfoFiles")
    public de.bund.bsi.ecard.api._1.DeleteCardInfoFilesResponse deleteCardInfoFiles(
        de.bund.bsi.ecard.api._1.DeleteCardInfoFiles parameters
    );

    @ECardApiMethod(operationName = "AddTrustedCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#AddTrustedCertificate")
    public de.bund.bsi.ecard.api._1.AddTrustedCertificateResponse addTrustedCertificate(
        de.bund.bsi.ecard.api._1.AddTrustedCertificate parameters
    );

    @ECardApiMethod(operationName = "AddCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#AddCertificate")
    public de.bund.bsi.ecard.api._1.AddCertificateResponse addCertificate(
        de.bund.bsi.ecard.api._1.AddCertificate parameters
    );

    @ECardApiMethod(operationName = "FrameworkUpdate", action = "http://www.bsi.bund.de/ecard/api/1.0#FrameworkUpdate")
    public de.bund.bsi.ecard.api._1.FrameworkUpdateResponse frameworkUpdate(
        de.bund.bsi.ecard.api._1.FrameworkUpdate parameters
    );

    @ECardApiMethod(operationName = "GetCardInfoList", action = "http://www.bsi.bund.de/ecard/api/1.0#GetCardInfoList")
    public de.bund.bsi.ecard.api._1.GetCardInfoListResponse getCardInfoList(
        de.bund.bsi.ecard.api._1.GetCardInfoList parameters
    );

    @ECardApiMethod(operationName = "SetCardInfoList", action = "http://www.bsi.bund.de/ecard/api/1.0#SetCardInfoList")
    public de.bund.bsi.ecard.api._1.SetCardInfoListResponse setCardInfoList(
        de.bund.bsi.ecard.api._1.SetCardInfoList parameters
    );

    @ECardApiMethod(operationName = "APIACLList", action = "http://www.bsi.bund.de/ecard/api/1.0#APIACLList")
    public de.bund.bsi.ecard.api._1.APIACLListResponse apiaclList(
        de.bund.bsi.ecard.api._1.APIACLList parameters
    );

    @ECardApiMethod(operationName = "SetTSServices", action = "http://www.bsi.bund.de/ecard/api/1.0#SetTSServices")
    public de.bund.bsi.ecard.api._1.SetTSServicesResponse setTSServices(
        de.bund.bsi.ecard.api._1.SetTSServices parameters
    );

    @ECardApiMethod(operationName = "DeleteCertificate", action = "http://www.bsi.bund.de/ecard/api/1.0#DeleteCertificate")
    public de.bund.bsi.ecard.api._1.DeleteCertificateResponse deleteCertificate(
        de.bund.bsi.ecard.api._1.DeleteCertificate parameters
    );
}
