package org.openecard.ws;

import java.util.Set;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@XmlSeeAlso({org.w3._2007._05.xmldsig_more_.ObjectFactory.class, org.w3._2001._04.xmlenc_.ObjectFactory.class, de.bund.bsi.ecard.api._1.ObjectFactory.class, org.etsi.uri._01903.v1_3.ObjectFactory.class, oasis.names.tc.dss_x._1_0.profiles.verificationreport.schema_.ObjectFactory.class, org.openecard.ws.schema.ObjectFactory.class, org.openecard.ws.chipgateway.ObjectFactory.class, org.w3._2001._04.xmldsig_more_.ObjectFactory.class, oasis.names.tc.dss._1_0.core.schema.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, generated.ObjectFactory.class, iso.std.iso_iec._24727.tech.schema.ObjectFactory.class, org.w3._2009.xmlenc11_.ObjectFactory.class, oasis.names.tc.saml._2_0.assertion.ObjectFactory.class, org.etsi.uri._02231.v3_1.ObjectFactory.class, oasis.names.tc.saml._1_0.assertion.ObjectFactory.class})
public interface SAL {

    /**
     * Gets a set of supported protocols of this SAL.
     *
     * @return Possibly empty set of protocols this SAL supports.
     */
    Set<String> supportedProtocols();

    /**
     * Creates a new session in the specified SAL.
     * <p>The following error codes (with prefix {@code http://www.bsi.bund.de/ecard/api/1.1/resultminor/sal}) are
     * defined for this method.</p>
     * <dl>
     * <dt>{@code #notInitialized}</dt>
     * <dd>The SAL is not initialized and can therefore not create sessions.</dd>
     * <dt>{@code #sessionAlreadyExists}</dt>
     * <dd>The requested session already exists.</dd>
     * <dt>{@code #insufficientResources}</dt>
     * <dd>Can not create more sessions.</dd>
     * <dt>/common#incorrectParameter</dt>
     * <dd>Invalid session ID given.</dd>
     * </dl>
     *
     * @param parameters The request may contain a session ID which shall be created.
     * @return Response containing the created session ID, or an error.
     */
    @ECardApiMethod(operationName = "CreateSession", action = "urn:iso:std:iso-iec:24727:tech:schema:CreateSession")
    public iso.std.iso_iec._24727.tech.schema.CreateSessionResponse createSession(
        iso.std.iso_iec._24727.tech.schema.CreateSession parameters
    );

    /**
     * Destroys an existing session in the specified SAL.
     * <p>A card connected in the session is automatically disconnected if that didn't happen with a
     * {@code CardApplicationDisconnect} before. That includes a reset of the card that is being disconnected.</p>
     * <p>The following error codes (with prefix {@code http://www.bsi.bund.de/ecard/api/1.1/resultminor/sal}) are
     * defined for this method.</p>
     * <dl>
     * <dt>{@code #notInitialized}</dt>
     * <dd>The SAL is not initialized and can therefore not create sessions.</dd>
     * <dt>{@code #NO_SESSION}</dt>
     * <dd>The requested session does not exist.</dd>
     * <dt>/common#incorrectParameter</dt>
     * <dd>Invalid connection handle given.</dd>
     * </dl>
     *
     * @param parameters The request must contain a connection handle identifying one session.
     * @return Response indicating success or failure.
     */
    @ECardApiMethod(operationName = "DestroySession", action = "urn:iso:std:iso-iec:24727:tech:schema:DestroySession")
    public iso.std.iso_iec._24727.tech.schema.DestroySessionResponse destroySession(
        iso.std.iso_iec._24727.tech.schema.DestroySession parameters
    );

    @ECardApiMethod(operationName = "CardApplicationList", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationList")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationListResponse cardApplicationList(
        iso.std.iso_iec._24727.tech.schema.CardApplicationList parameters
    );

    @ECardApiMethod(operationName = "CardApplicationServiceLoad", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationServiceLoad")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationServiceLoadResponse cardApplicationServiceLoad(
        iso.std.iso_iec._24727.tech.schema.CardApplicationServiceLoad parameters
    );

    @ECardApiMethod(operationName = "Hash", action = "urn:iso:std:iso-iec:24727:tech:schema:Hash")
    public iso.std.iso_iec._24727.tech.schema.HashResponse hash(
        iso.std.iso_iec._24727.tech.schema.Hash parameters
    );

    @ECardApiMethod(operationName = "Initialize", action = "urn:iso:std:iso-iec:24727:tech:schema:Initialize")
    public iso.std.iso_iec._24727.tech.schema.InitializeResponse initialize(
        iso.std.iso_iec._24727.tech.schema.Initialize parameters
    );

    @ECardApiMethod(operationName = "Terminate", action = "urn:iso:std:iso-iec:24727:tech:schema:Terminate")
    public iso.std.iso_iec._24727.tech.schema.TerminateResponse terminate(
        iso.std.iso_iec._24727.tech.schema.Terminate parameters
    );

    @ECardApiMethod(operationName = "CardApplicationDelete", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationDelete")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationDeleteResponse cardApplicationDelete(
        iso.std.iso_iec._24727.tech.schema.CardApplicationDelete parameters
    );

    @ECardApiMethod(operationName = "VerifyCertificate", action = "urn:iso:std:iso-iec:24727:tech:schema:VerifyCertificate")
    public iso.std.iso_iec._24727.tech.schema.VerifyCertificateResponse verifyCertificate(
        iso.std.iso_iec._24727.tech.schema.VerifyCertificate parameters
    );

    @ECardApiMethod(operationName = "CardApplicationSelect", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationSelect")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationSelectResponse cardApplicationSelect(
        iso.std.iso_iec._24727.tech.schema.CardApplicationSelect parameters
    );

    @ECardApiMethod(operationName = "CardApplicationServiceList", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationServiceList")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationServiceListResponse cardApplicationServiceList(
        iso.std.iso_iec._24727.tech.schema.CardApplicationServiceList parameters
    );

    @ECardApiMethod(operationName = "CardApplicationDisconnect", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationDisconnect")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationDisconnectResponse cardApplicationDisconnect(
        iso.std.iso_iec._24727.tech.schema.CardApplicationDisconnect parameters
    );

    @ECardApiMethod(operationName = "DSIDelete", action = "urn:iso:std:iso-iec:24727:tech:schema:DSIDelete")
    public iso.std.iso_iec._24727.tech.schema.DSIDeleteResponse dsiDelete(
        iso.std.iso_iec._24727.tech.schema.DSIDelete parameters
    );

    @ECardApiMethod(operationName = "GetRandom", action = "urn:iso:std:iso-iec:24727:tech:schema:GetRandom")
    public iso.std.iso_iec._24727.tech.schema.GetRandomResponse getRandom(
        iso.std.iso_iec._24727.tech.schema.GetRandom parameters
    );

    @ECardApiMethod(operationName = "DIDList", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDList")
    public iso.std.iso_iec._24727.tech.schema.DIDListResponse didList(
        iso.std.iso_iec._24727.tech.schema.DIDList parameters
    );

    @ECardApiMethod(operationName = "DIDGet", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDGet")
    public iso.std.iso_iec._24727.tech.schema.DIDGetResponse didGet(
        iso.std.iso_iec._24727.tech.schema.DIDGet parameters
    );

    @ECardApiMethod(operationName = "ExecuteAction", action = "urn:iso:std:iso-iec:24727:tech:schema:ExecuteAction")
    public iso.std.iso_iec._24727.tech.schema.ExecuteActionResponse executeAction(
        iso.std.iso_iec._24727.tech.schema.ExecuteAction parameters
    );

    @ECardApiMethod(operationName = "DataSetList", action = "urn:iso:std:iso-iec:24727:tech:schema:DataSetList")
    public iso.std.iso_iec._24727.tech.schema.DataSetListResponse dataSetList(
        iso.std.iso_iec._24727.tech.schema.DataSetList parameters
    );

    @ECardApiMethod(operationName = "DataSetSelect", action = "urn:iso:std:iso-iec:24727:tech:schema:DataSetSelect")
    public iso.std.iso_iec._24727.tech.schema.DataSetSelectResponse dataSetSelect(
        iso.std.iso_iec._24727.tech.schema.DataSetSelect parameters
    );

    @ECardApiMethod(operationName = "ACLModify", action = "urn:iso:std:iso-iec:24727:tech:schema:ACLModify")
    public iso.std.iso_iec._24727.tech.schema.ACLModifyResponse aclModify(
        iso.std.iso_iec._24727.tech.schema.ACLModify parameters
    );

    @ECardApiMethod(operationName = "Encipher", action = "urn:iso:std:iso-iec:24727:tech:schema:Encipher")
    public iso.std.iso_iec._24727.tech.schema.EncipherResponse encipher(
        iso.std.iso_iec._24727.tech.schema.Encipher parameters
    );

    @ECardApiMethod(operationName = "CardApplicationCreate", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationCreate")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationCreateResponse cardApplicationCreate(
        iso.std.iso_iec._24727.tech.schema.CardApplicationCreate parameters
    );

    @ECardApiMethod(operationName = "CardApplicationConnect", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationConnect")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationConnectResponse cardApplicationConnect(
        iso.std.iso_iec._24727.tech.schema.CardApplicationConnect parameters
    );

    @ECardApiMethod(operationName = "DSICreate", action = "urn:iso:std:iso-iec:24727:tech:schema:DSICreate")
    public iso.std.iso_iec._24727.tech.schema.DSICreateResponse dsiCreate(
        iso.std.iso_iec._24727.tech.schema.DSICreate parameters
    );

    @ECardApiMethod(operationName = "DSIList", action = "urn:iso:std:iso-iec:24727:tech:schema:DSIList")
    public iso.std.iso_iec._24727.tech.schema.DSIListResponse dsiList(
        iso.std.iso_iec._24727.tech.schema.DSIList parameters
    );

    @ECardApiMethod(operationName = "VerifySignature", action = "urn:iso:std:iso-iec:24727:tech:schema:VerifySignature")
    public iso.std.iso_iec._24727.tech.schema.VerifySignatureResponse verifySignature(
        iso.std.iso_iec._24727.tech.schema.VerifySignature parameters
    );

    @ECardApiMethod(operationName = "DIDCreate", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDCreate")
    public iso.std.iso_iec._24727.tech.schema.DIDCreateResponse didCreate(
        iso.std.iso_iec._24727.tech.schema.DIDCreate parameters
    );

    @ECardApiMethod(operationName = "CardApplicationEndSession", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationEndSession")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationEndSessionResponse cardApplicationEndSession(
        iso.std.iso_iec._24727.tech.schema.CardApplicationEndSession parameters
    );

    @ECardApiMethod(operationName = "DIDAuthenticate", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDAuthenticate")
    public iso.std.iso_iec._24727.tech.schema.DIDAuthenticateResponse didAuthenticate(
        iso.std.iso_iec._24727.tech.schema.DIDAuthenticate parameters
    );

    @ECardApiMethod(operationName = "DataSetCreate", action = "urn:iso:std:iso-iec:24727:tech:schema:DataSetCreate")
    public iso.std.iso_iec._24727.tech.schema.DataSetCreateResponse dataSetCreate(
        iso.std.iso_iec._24727.tech.schema.DataSetCreate parameters
    );

    @ECardApiMethod(operationName = "DSIWrite", action = "urn:iso:std:iso-iec:24727:tech:schema:DSIWrite")
    public iso.std.iso_iec._24727.tech.schema.DSIWriteResponse dsiWrite(
        iso.std.iso_iec._24727.tech.schema.DSIWrite parameters
    );

    @ECardApiMethod(operationName = "CardApplicationServiceDelete", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationServiceDelete")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationServiceDeleteResponse cardApplicationServiceDelete(
        iso.std.iso_iec._24727.tech.schema.CardApplicationServiceDelete parameters
    );

    @ECardApiMethod(operationName = "DSIRead", action = "urn:iso:std:iso-iec:24727:tech:schema:DSIRead")
    public iso.std.iso_iec._24727.tech.schema.DSIReadResponse dsiRead(
        iso.std.iso_iec._24727.tech.schema.DSIRead parameters
    );

    @ECardApiMethod(operationName = "DIDUpdate", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDUpdate")
    public iso.std.iso_iec._24727.tech.schema.DIDUpdateResponse didUpdate(
        iso.std.iso_iec._24727.tech.schema.DIDUpdate parameters
    );

    @ECardApiMethod(operationName = "Sign", action = "urn:iso:std:iso-iec:24727:tech:schema:Sign")
    public iso.std.iso_iec._24727.tech.schema.SignResponse sign(
        iso.std.iso_iec._24727.tech.schema.Sign parameters
    );

    @ECardApiMethod(operationName = "DIDDelete", action = "urn:iso:std:iso-iec:24727:tech:schema:DIDDelete")
    public iso.std.iso_iec._24727.tech.schema.DIDDeleteResponse didDelete(
        iso.std.iso_iec._24727.tech.schema.DIDDelete parameters
    );

    @ECardApiMethod(operationName = "CardApplicationStartSession", action = "urn:iso:std:iso-iec:24727:tech:schema:StartSession")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationStartSessionResponse cardApplicationStartSession(
        iso.std.iso_iec._24727.tech.schema.CardApplicationStartSession parameters
    );

    @ECardApiMethod(operationName = "Decipher", action = "urn:iso:std:iso-iec:24727:tech:schema:Decipher")
    public iso.std.iso_iec._24727.tech.schema.DecipherResponse decipher(
        iso.std.iso_iec._24727.tech.schema.Decipher parameters
    );

    @ECardApiMethod(operationName = "CardApplicationServiceDescribe", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationServiceDescribe")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationServiceDescribeResponse cardApplicationServiceDescribe(
        iso.std.iso_iec._24727.tech.schema.CardApplicationServiceDescribe parameters
    );

    @ECardApiMethod(operationName = "CardApplicationPath", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationPath")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationPathResponse cardApplicationPath(
        iso.std.iso_iec._24727.tech.schema.CardApplicationPath parameters
    );

    @ECardApiMethod(operationName = "CardApplicationServiceCreate", action = "urn:iso:std:iso-iec:24727:tech:schema:CardApplicationServiceCreate")
    public iso.std.iso_iec._24727.tech.schema.CardApplicationServiceCreateResponse cardApplicationServiceCreate(
        iso.std.iso_iec._24727.tech.schema.CardApplicationServiceCreate parameters
    );

    @ECardApiMethod(operationName = "DataSetDelete", action = "urn:iso:std:iso-iec:24727:tech:schema:DataSetDelete")
    public iso.std.iso_iec._24727.tech.schema.DataSetDeleteResponse dataSetDelete(
        iso.std.iso_iec._24727.tech.schema.DataSetDelete parameters
    );

    @ECardApiMethod(operationName = "ACLList", action = "urn:iso:std:iso-iec:24727:tech:schema:ACLList")
    public iso.std.iso_iec._24727.tech.schema.ACLListResponse aclList(
        iso.std.iso_iec._24727.tech.schema.ACLList parameters
    );
}
