compile:
  stage: compile
  image: docker.io/cimg/android:2025.09
  tags:
    - "podman"
  cache:
    - key: "$OEC_JAVA_CACHE_KEY"
      paths: !reference [ .cache-gradle-base, paths ]
      policy: pull-push
    - key: "$OEC_JAVA_TMP_CACHE_KEY"
      paths: [ .cache-gradle-builds, paths ]
      policy: pull-push
  script:
    - !reference [.versioning, script]
    - ./gradlew assemble
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "master"
