package-linux:
  stage: package
  image: public.docker.ecsec.de/ecsec/tools/oec-linux-installer:2.0
  tags:
    - "podman"
  cache:
  - key: "$OEC_JAVA_CACHE_KEY"
    paths: !reference [ .cache-gradle-base, paths ]
    policy: pull
  - key: "$OEC_JAVA_TMP_CACHE_KEY"
    paths: [ .cache-gradle-builds, paths ]
    policy: pull
  artifacts:
    name: 'OeC-Installer-Linux'
    paths:
      - clients/richclient/build/dist
  script:
    - !reference [.versioning, script]
    - ./gradlew packageLinux
  needs: [ "compile" ]
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
    - if: $CI_MERGE_REQUEST_IID
      when: manual
      allow_failure: true
