collect-installers:
  stage: post-package
  image: docker.io/alpine:latest
  tags:
    - "podman"
  artifacts:
    name: 'OeC-Installers'
    paths:
      - "*.deb"
      - "*.rpm"
      - "*.dmg"
      - "*.pkg"
      - "*.exe"
  script:
    - >-
      cp  clients/richclient/build/dist/PKG/*.pkg \
          clients/richclient/build/dist/DMG/*.dmg \
          clients/richclient/build/dist/DEB/*.deb \
          clients/richclient/build/dist/RPM/*.rpm \
          clients/richclient/build/dist/EXE/*.exe \
          .
  dependencies:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  needs:
    - "package-linux"
    - "package-win"
    - "notarize-osx"
  rules:
    - if: $CI_COMMIT_TAG =~ /^richclient-v\d+\.\d+\.\d+(-rc.\d+)?$/
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_MERGE_REQUEST_IID
      allow_failure: true
