package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_RSA_PKCS_OAEP_PARAMS extends Structure {
	/** C type : CK_MECHANISM_TYPE */
	public long hashAlg;
	public long getHashAlg() {
		return hashAlg;
	}
	public void setHashAlg(long hashAlg) {
		this.hashAlg = hashAlg;
	}
	/** C type : CK_RSA_PKCS_MGF_TYPE */
	public long mgf;
	public long getMgf() {
		return mgf;
	}
	public void setMgf(long mgf) {
		this.mgf = mgf;
	}
	/** C type : CK_RSA_PKCS_OAEP_SOURCE_TYPE */
	public long source;
	public long getSource() {
		return source;
	}
	public void setSource(long source) {
		this.source = source;
	}
	/** C type : CK_VOID_PTR */
	public Pointer pSourceData;
	public Pointer getPSourceData() {
		return pSourceData;
	}
	public void setPSourceData(Pointer pSourceData) {
		this.pSourceData = pSourceData;
	}
	/** C type : CK_ULONG */
	public long ulSourceDataLen;
	public long getUlSourceDataLen() {
		return ulSourceDataLen;
	}
	public void setUlSourceDataLen(long ulSourceDataLen) {
		this.ulSourceDataLen = ulSourceDataLen;
	}
	public CK_RSA_PKCS_OAEP_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("hashAlg", "mgf", "source", "pSourceData", "ulSourceDataLen");
	}
	/**
	 * @param hashAlg C type : CK_MECHANISM_TYPE<br>
	 * @param mgf C type : CK_RSA_PKCS_MGF_TYPE<br>
	 * @param source C type : CK_RSA_PKCS_OAEP_SOURCE_TYPE<br>
	 * @param pSourceData C type : CK_VOID_PTR<br>
	 * @param ulSourceDataLen C type : CK_ULONG
	 */
	public CK_RSA_PKCS_OAEP_PARAMS(long hashAlg, long mgf, long source, Pointer pSourceData, long ulSourceDataLen) {
		super();
		this.hashAlg = hashAlg;
		this.mgf = mgf;
		this.source = source;
		this.pSourceData = pSourceData;
		this.ulSourceDataLen = ulSourceDataLen;
	}
	public CK_RSA_PKCS_OAEP_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_RSA_PKCS_OAEP_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_RSA_PKCS_OAEP_PARAMS implements Structure.ByValue {
		
	};
}
