package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_RSA_AES_KEY_WRAP_PARAMS extends Structure {
	/** C type : CK_ULONG */
	public long ulAESKeyBits;
	public long getUlAESKeyBits() {
		return ulAESKeyBits;
	}
	public void setUlAESKeyBits(long ulAESKeyBits) {
		this.ulAESKeyBits = ulAESKeyBits;
	}
	/** C type : CK_RSA_PKCS_OAEP_PARAMS_PTR */
	public org.openecard.mdlw.sal.cryptoki.CK_RSA_PKCS_OAEP_PARAMS.ByReference pOAEPParams;
	public org.openecard.mdlw.sal.cryptoki.CK_RSA_PKCS_OAEP_PARAMS.ByReference getPOAEPParams() {
		return pOAEPParams;
	}
	public void setPOAEPParams(org.openecard.mdlw.sal.cryptoki.CK_RSA_PKCS_OAEP_PARAMS.ByReference pOAEPParams) {
		this.pOAEPParams = pOAEPParams;
	}
	public CK_RSA_AES_KEY_WRAP_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("ulAESKeyBits", "pOAEPParams");
	}
	/**
	 * @param ulAESKeyBits C type : CK_ULONG<br>
	 * @param pOAEPParams C type : CK_RSA_PKCS_OAEP_PARAMS_PTR
	 */
	public CK_RSA_AES_KEY_WRAP_PARAMS(long ulAESKeyBits, org.openecard.mdlw.sal.cryptoki.CK_RSA_PKCS_OAEP_PARAMS.ByReference pOAEPParams) {
		super();
		this.ulAESKeyBits = ulAESKeyBits;
		this.pOAEPParams = pOAEPParams;
	}
	public CK_RSA_AES_KEY_WRAP_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_RSA_AES_KEY_WRAP_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_RSA_AES_KEY_WRAP_PARAMS implements Structure.ByValue {
		
	};
}
