package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_RC5_CBC_PARAMS extends Structure {
	/**
	 * wordsize in bits<br>
	 * C type : CK_ULONG
	 */
	public long ulWordsize;
	public long getUlWordsize() {
		return ulWordsize;
	}
	public void setUlWordsize(long ulWordsize) {
		this.ulWordsize = ulWordsize;
	}
	/**
	 * number of rounds<br>
	 * C type : CK_ULONG
	 */
	public long ulRounds;
	public long getUlRounds() {
		return ulRounds;
	}
	public void setUlRounds(long ulRounds) {
		this.ulRounds = ulRounds;
	}
	/**
	 * pointer to IV<br>
	 * C type : CK_BYTE_PTR
	 */
	public Pointer pIv;
	public Pointer getPIv() {
		return pIv;
	}
	public void setPIv(Pointer pIv) {
		this.pIv = pIv;
	}
	/**
	 * length of IV in bytes<br>
	 * C type : CK_ULONG
	 */
	public long ulIvLen;
	public long getUlIvLen() {
		return ulIvLen;
	}
	public void setUlIvLen(long ulIvLen) {
		this.ulIvLen = ulIvLen;
	}
	public CK_RC5_CBC_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("ulWordsize", "ulRounds", "pIv", "ulIvLen");
	}
	/**
	 * @param ulWordsize wordsize in bits<br>
	 * C type : CK_ULONG<br>
	 * @param ulRounds number of rounds<br>
	 * C type : CK_ULONG<br>
	 * @param pIv pointer to IV<br>
	 * C type : CK_BYTE_PTR<br>
	 * @param ulIvLen length of IV in bytes<br>
	 * C type : CK_ULONG
	 */
	public CK_RC5_CBC_PARAMS(long ulWordsize, long ulRounds, Pointer pIv, long ulIvLen) {
		super();
		this.ulWordsize = ulWordsize;
		this.ulRounds = ulRounds;
		this.pIv = pIv;
		this.ulIvLen = ulIvLen;
	}
	public CK_RC5_CBC_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_RC5_CBC_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_RC5_CBC_PARAMS implements Structure.ByValue {
		
	};
}
