package org.openecard.mdlw.sal.cryptoki;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : pkcs11_v2.40/pkcs11t.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CK_TLS_KDF_PARAMS extends Structure {
	/** C type : CK_MECHANISM_TYPE */
	public long prfMechanism;
	public long getPrfMechanism() {
		return prfMechanism;
	}
	public void setPrfMechanism(long prfMechanism) {
		this.prfMechanism = prfMechanism;
	}
	/** C type : CK_BYTE_PTR */
	public Pointer pLabel;
	public Pointer getPLabel() {
		return pLabel;
	}
	public void setPLabel(Pointer pLabel) {
		this.pLabel = pLabel;
	}
	/** C type : CK_ULONG */
	public long ulLabelLength;
	public long getUlLabelLength() {
		return ulLabelLength;
	}
	public void setUlLabelLength(long ulLabelLength) {
		this.ulLabelLength = ulLabelLength;
	}
	/** C type : CK_SSL3_RANDOM_DATA */
	public CK_SSL3_RANDOM_DATA RandomInfo;
	public CK_SSL3_RANDOM_DATA getRandomInfo() {
		return RandomInfo;
	}
	public void setRandomInfo(CK_SSL3_RANDOM_DATA RandomInfo) {
		this.RandomInfo = RandomInfo;
	}
	/** C type : CK_BYTE_PTR */
	public Pointer pContextData;
	public Pointer getPContextData() {
		return pContextData;
	}
	public void setPContextData(Pointer pContextData) {
		this.pContextData = pContextData;
	}
	/** C type : CK_ULONG */
	public long ulContextDataLength;
	public long getUlContextDataLength() {
		return ulContextDataLength;
	}
	public void setUlContextDataLength(long ulContextDataLength) {
		this.ulContextDataLength = ulContextDataLength;
	}
	public CK_TLS_KDF_PARAMS() {
		super();
	}
	 protected List<String> getFieldOrder() {
		return Arrays.asList("prfMechanism", "pLabel", "ulLabelLength", "RandomInfo", "pContextData", "ulContextDataLength");
	}
	/**
	 * @param prfMechanism C type : CK_MECHANISM_TYPE<br>
	 * @param pLabel C type : CK_BYTE_PTR<br>
	 * @param ulLabelLength C type : CK_ULONG<br>
	 * @param RandomInfo C type : CK_SSL3_RANDOM_DATA<br>
	 * @param pContextData C type : CK_BYTE_PTR<br>
	 * @param ulContextDataLength C type : CK_ULONG
	 */
	public CK_TLS_KDF_PARAMS(long prfMechanism, Pointer pLabel, long ulLabelLength, CK_SSL3_RANDOM_DATA RandomInfo, Pointer pContextData, long ulContextDataLength) {
		super();
		this.prfMechanism = prfMechanism;
		this.pLabel = pLabel;
		this.ulLabelLength = ulLabelLength;
		this.RandomInfo = RandomInfo;
		this.pContextData = pContextData;
		this.ulContextDataLength = ulContextDataLength;
	}
	public CK_TLS_KDF_PARAMS(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CK_TLS_KDF_PARAMS implements Structure.ByReference {
		
	};
	public static class ByValue extends CK_TLS_KDF_PARAMS implements Structure.ByValue {
		
	};
}
